var first_name = 'Brian';
var last_name = 'Shin';
var age = '29';
var date_of_birth = '12/16/1990';
var address = '1008 Gilroy Crescent';
console.log(first_name);
console.log(last_name);
console.log(age);
console.log(date_of_birth);
console.log(address);