number = 9;
console.log(number + ' times 1 equals ' + number * 1)
console.log(number + ' times 1 equals ' + number * 2)
console.log(number + ' times 1 equals ' + number * 3)
console.log(number + ' times 1 equals ' + number * 4)
console.log(number + ' times 1 equals ' + number * 5)
console.log(number + ' times 1 equals ' + number * 6)
console.log(number + ' times 1 equals ' + number * 7)
console.log(number + ' times 1 equals ' + number * 8)
console.log(number + ' times 1 equals ' + number * 9)
console.log(number + ' times 1 equals ' + number * 10)