const first_name = 'Brian';
const last_name = 'Shin';
const age = '29';
const date_of_birth = '12/16/1990';
const address = '1008 Gilroy Crescent';
console.log('First Name: ', first_name);
console.log('Last Name: ', last_name);
console.log('Age: ', age);
console.log('Date of Birth: ', date_of_birth);
console.log('Address: ', address);