var first_name = 'Brian';
var last_name = 'Shin';
var age = '29';
var date_of_birth = '12/16/1990';
var address = '1008 Gilroy Crescent';
console.log('First Name: ', first_name);
console.log('Last Name: ', last_name);
console.log('Age: ', age);
console.log('Date of Birth: ', date_of_birth);
console.log('Address: ', address);