const Logger = require('logplease')
const logger = Logger.create('ex3')
logger.debug(`Hello Node.js`)
logger.info(`Node.js is great!!`)
logger.warn(`Warning, warning, I think we have a warning`)
logger.error(`Mayday, Mayday, we have an error, repeat.. we have an error`)